name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Upload project excluding .git
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "~/PlayForYou/backend"
          rm: true
          strip_components: 0
          exclude: ".git"

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/PlayForYou/backend
            # .env 파일 생성
            cat <<EOF > .env
            ${{ secrets.ENV_PROD }}
            EOF
            # Docker 재배포
            docker compose down
            docker compose up -d --build